services:
  frontend-app:
    ports:
      - "5173:5173"
    build:
      context: ./frontend/DrMentation
      dockerfile: Dockerfile
    volumes:
      - ./frontend/DrMentation:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  backend-api-v2:
    build:
      context: ./api/v2
      dockerfile: Dockerfile
    ports:
      - 5045:5045
    volumes:
      - ./api/v2:/app
      depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db

