version: '3.4'

services:
  backend-api:
    ports:
      - "5045:80"
    build:
      context: ./api/DrMentation
      dockerfile: docker/Dockerfile
    volumes:
      - ./api/DrMentation:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

