services:
  #   backend-api:
  #     ports:
  #       - "5045:80"
  #     build:
  #       context: ./api/DrMentation
  #       dockerfile: docker/Dockerfile
  #     volumes:
  #       - ./api/DrMentation:/app
  #       - /app/bin
  #       - /app/obj
  #     environment:
  #       - ASPNETCORE_ENVIRONMENT=Development

  frontend-app:
    ports:
      - "5173:5173"
    build:
      context: ./frontend/DrMentation
      dockerfile: Dockerfile
    volumes:
      - ./frontend/DrMentation:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend-api-v2:
    build:
      context: ./api/v2
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./api/v2:/app
